[project]
name = "htmls-hw"
version = "0.1.0"
description = ""
authors = [
    {name = "Vasiliy"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.2,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = ">=3.13,<4.0"


[tool.poetry.group.devtools.dependencies]
django = "^6.0.2"
black = "^26.1.0"
isort = "^8.0.0"


[tool.poetry.group.tools.dependencies]
python-dotenv = "^1.2.1"
dotenv = "^0.9.9"
psycopg2-binary = "^2.9.11"
pillow = "^12.1.1"
ipython = "^9.10.0"
langchain-community = "^0.4.1"
langchain-openai = "^1.1.11"


[isort]
max-line_length = 119


[tool.isort]
profile = "black"


[black]
max-line-length = 119
exclude = ".*\\.git.*"
