# Generated by Django 6.0.2 on 2026-04-11 20:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("World", "Мировые"),
                            ("Russia", "Россия"),
                            ("Technology", "Технологии"),
                            ("Design", "Дизайн"),
                            ("Culture", "Культура"),
                            ("Business", "Бизнес"),
                            ("Politics", "Политика"),
                            ("Opinion", "Мнение"),
                            ("Science", "Наука"),
                            ("Health", "Здоровье"),
                            ("Style", "Стиль"),
                            ("Travel", "Путешествия"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=60, unique=True, verbose_name="URL-адрес"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Эмодзи-иконка"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Эмодзи-иконка"
                    ),
                ),
                ("text", models.TextField(max_length=1000, verbose_name="Комментарий")),
                ("slug", models.SlugField(max_length=60, verbose_name="URL-адрес")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.get_comment_media_path,
                        verbose_name="Изображение к комментарию",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.get_comment_media_path,
                        verbose_name="Видео к комментарию",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата написания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("is_formatted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок поста"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Cодержание"),
                ),
                (
                    "about_content",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Кратко о содержании",
                    ),
                ),
                (
                    "viewed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[("YES", "Опубликовать"), ("NO", "Позже")],
                        default="NO",
                        max_length=12,
                        verbose_name="Опубликовать сразу",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Когда опубликовать?"
                    ),
                ),
                ("published_at", models.DateField(verbose_name="Дата публикации")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "popularity",
                    models.IntegerField(default=0, verbose_name="Популярность"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик лайков"
                    ),
                ),
                (
                    "dislikes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик дизлайков"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("is_formatted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "author", "-created_at", "tag"],
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.get_upload_path_pm,
                        verbose_name="Изображение поста",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.get_upload_path_pm,
                        verbose_name="Превью поста",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.get_upload_path_pm,
                        verbose_name="Видео-презентация продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа поста",
                "verbose_name_plural": "Медиа постов",
            },
        ),
    ]
