# Generated by Django 6.0.2 on 2026-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_image_remove_product_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/image",
                verbose_name="Изображение категории",
            ),
        ),
        migrations.DeleteModel(
            name="CategoryMedia",
        ),
    ]
