# Generated by Django 6.0.2 on 2026-03-12 18:01

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_category_image_delete_categorymedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.Category.get_upload_path,
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=catalog.models.ProductMedia.get_upload_path,
                verbose_name="Изображение продукта",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=catalog.models.ProductMedia.get_upload_path,
                verbose_name="Видео-презентация продукта",
            ),
        ),
    ]
